# Generated by Django 4.0.6 on 2022-07-21 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('rasm', models.FileField(upload_to='bolimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Ichki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('rasm', models.FileField(upload_to='ichkilar')),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('narx', models.IntegerField()),
                ('ishlab_ch', models.CharField(max_length=20)),
                ('kafolat', models.CharField(max_length=30)),
                ('yetkazish', models.CharField(max_length=50)),
                ('mavjud', models.BooleanField(default=True)),
                ('batafsil', models.CharField(max_length=500)),
                ('ichki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.ichki')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='mahsulotlar')),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.mahsulot')),
            ],
        ),
    ]
